package com.br.requirementhub.enums;

public enum Permissions {
    APROVAR_REQUISITO,
    EXCLUIR_REQUISITO,
    EDITAR_REQUISITO,
    VISUALIZAR_REQUISITO,
    APROVAR_DOCUMENTO,
    EXCLUIR_DOCUMENTO,
    EDITAR_DOCUMENTO,
    VISUALIZAR_DOCUMENTO,
    APROVAR_PROJETO,
    EXCLUIR_PROJETO,
    EDITAR_PROJETO,
    VISUALIZAR_PROJETO,
    APROVAR_REQUISITO_PROJETO,
    EXCLUIR_REQUISITO_PROJETO,
    EDITAR_REQUISITO_PROJETO,
    VISUALIZAR_REQUISITO_PROJETO,
    APROVAR_DOCUMENTO_PROJETO,
    EXCLUIR_DOCUMENTO_PROJETO,
    EDITAR_DOCUMENTO_PROJETO,
    VISUALIZAR_DOCUMENTO_PROJETO,
    VALIDAR_PROJETO,
    COMPLEMENTAR_REQUISITO,

}
