package com.br.requirementhub.enums;

public enum Status {
    BLOQUEADO,
    ATIVO,
    EM_CADASTRO,
    AGUARDANDO_INDICACAO_RESPONSAVEL,
    EM_ANALISE_DE_REQUISTOS,
    EM_ESPECIFICACAO,
    EM_APROVACAO_ESPECIFICACAO,
    AGUARDANDO_COMPLEMENTO_OU_EXCLUSAO,
    EXCLUIDO,
    VALIDADO
}
